# docker/nginx/Dockerfile
FROM nginx:1.23
ADD myproj.nginx.conf /etc/nginx/conf.d/default.conf
#ADD myprojlb.nginx.conf /etc/nginx/nginx.conf

#root@debianfran1:/home/myDockerProject# docker exec -it nginx /bin/sh

# chmod -R ugo+rw var/www/html/myproj/storage

#RUN rm -rf /var/www/html && mv /src/test /var/www/html/myproj &&\
#    find /var/www/html/ -type d -exec chmod 755 {} \; &&\
#    find /var/www/html/ -type f -exec chmod 644 {} \; &&\
#    chmod -R 777 /var/www/html/myproj/cache /var/www/html/myproj/logs